apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: <your-volume-id>
