apiVersion: v1
kind: Service
metadata:
  name: nexus-oss
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: nexus
